version: "3"

services: 
    peerbridge:
        image: peerbridge/peerbridge
        build: 
            context: ../
            dockerfile: deployments/Dockerfile
        ports: 
            - "8000:8000"