version: "3"

services:
    peerbridge:
        image: peerbridge/peerbridge
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            PORT: "8080"
            # Alice's private key
            PRIVATE_KEY: "eba4f82788edb8e464920293ff06605484bef87561880e44b6e4902f27e6d6ca"
            DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@database:5432/postgres?sslmode=disable}

    database:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-peerbridge}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}

    adminer:
        image: adminer:4.7-standalone
        ports:
            - 9000:8080
