name: Push Container to Heroku
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: '${{ secrets.HEROKU_API_KEY }}'
        run: 'heroku container:login'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: '${{ runner.os }}-buildx-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        id: build
        uses: docker/build-push-action@v2
        env:
          HEROKU_API_KEY: '${{ secrets.HEROKU_API_KEY }}'
        with:
          push: true
          context: .
          tags: registry.heroku.com/peerbridge/web
          cache-from: 'type=local,src=/tmp/.buildx-cache'
          cache-to: 'type=local,dest=/tmp/.buildx-cache-new'

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: 'echo ${{ steps.build.outputs.digest }}'

      - name: Release
        env:
          HEROKU_API_KEY: '${{ secrets.HEROKU_API_KEY }}'
        run: 'heroku container:release --app ${{ secrets.HEROKU_APP_NAME }} web'

